// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAC5sBhfHzRw1gBfmZ6MefW80xjpyVd0I',
    appId: '1:943095534116:web:7d0f33e65f3893cac3feb1',
    messagingSenderId: '943095534116',
    projectId: 'pazaryeri-57419',
    authDomain: 'pazaryeri-57419.firebaseapp.com',
    storageBucket: 'pazaryeri-57419.firebasestorage.app',
    measurementId: 'G-428ZW5YT64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxj6us9SVAj5-7kEJ_R3nEvBm_Js1XPnU',
    appId: '1:943095534116:android:0196bfc11c44f8bcc3feb1',
    messagingSenderId: '943095534116',
    projectId: 'pazaryeri-57419',
    storageBucket: 'pazaryeri-57419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxn_JLvXGYy6bg7P6s4H03aoNFvHDXl0Y',
    appId: '1:943095534116:ios:72331ef3657d2eccc3feb1',
    messagingSenderId: '943095534116',
    projectId: 'pazaryeri-57419',
    storageBucket: 'pazaryeri-57419.firebasestorage.app',
    androidClientId: '943095534116-lnnp0q4g3f7ibu098b9snuq6ilrki9kc.apps.googleusercontent.com',
    iosClientId: '943095534116-pf4a7geipc7vljmeds7ud12odu6oe56i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxn_JLvXGYy6bg7P6s4H03aoNFvHDXl0Y',
    appId: '1:943095534116:ios:72331ef3657d2eccc3feb1',
    messagingSenderId: '943095534116',
    projectId: 'pazaryeri-57419',
    storageBucket: 'pazaryeri-57419.firebasestorage.app',
    androidClientId: '943095534116-lnnp0q4g3f7ibu098b9snuq6ilrki9kc.apps.googleusercontent.com',
    iosClientId: '943095534116-pf4a7geipc7vljmeds7ud12odu6oe56i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAC5sBhfHzRw1gBfmZ6MefW80xjpyVd0I',
    appId: '1:943095534116:web:f35dddb45494960dc3feb1',
    messagingSenderId: '943095534116',
    projectId: 'pazaryeri-57419',
    authDomain: 'pazaryeri-57419.firebaseapp.com',
    storageBucket: 'pazaryeri-57419.firebasestorage.app',
    measurementId: 'G-N2TRPRJ1QJ',
  );

}