class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'home_title': 'PAZARYERİ',
      'account_title': 'HESABIM',
      'login': 'Giriş Yap',
      'login_success': 'Giriş başarılı. Hoş geldiniz!',
      'logout': 'Çıkış Yap',
      'register': 'Kayıt Ol',
      'dark_mode': 'Karanlık Mod',
      'language': 'Dil / Language',
      'welcome': 'Hoş geldin',
      'guest_login_success': 'Misafir olarak giriş yapıldı.',
      'guest_message':
          'Hesabım alanını görüntülemek ve kişisel avantajlardan yararlanmak için lütfen giriş yapın.',
      'edit_profile': 'Profili Düzenle',
      'create_account': 'Hesap Oluştur',
      'search_hint': 'Ürün ara (ör: elma)',
      'nearby_markets': 'En Yakın Semt Pazarları',
      'see_all': 'Tümünü Gör',
      'all_markets': 'Tüm Pazarlar',
      'settings': 'Ayarlar',
      'location_refresh': 'Konumu Yenile',
      'customer_label': 'Müşteri',
      'seller_label': 'Satıcı',
      'select_user_type': 'Giriş Türü Seçin',
      'seller_login': 'Satıcı Girişi',
      'email_not_verified_message':
          'E-posta adresiniz doğrulanmamış. Lütfen gelen kutunuzu kontrol edin.',
      'resend_verification_email': 'Doğrulama E-postasını Tekrar Gönder',
      'verification_email_sent_success':
          'Doğrulama e-postası tekrar gönderildi.',
      'cancel': 'İptal',
      'remember_me': 'Beni Hatırla',
      'search_tab': 'ARA',
      'products_tab': 'ÜRÜNLER',
      'report_tab': 'BİLDİR',
      'logout_success': 'Oturum kapatıldı.',
      'location_title': 'Tam Konum',
      'city': 'Şehir',
      'coordinate': 'Koordinat',
      'location_updated': 'Konum güncellendi',
      'markets_loaded': 'pazar yüklendi',
      'unknown': 'bilinmiyor',
      'selected_province': 'Seçilen il',
      'search_province_hint': 'İl ara (örn: İst veya An)',
      'clear_selection': 'Seçimi Temizle',
      'error_prefix': 'Hata',
      'location_settings': 'Konum ayarları',
      'retry': 'Yeniden Dene',
      'province_not_found': 'iline ait pazar bulunamadı.',
      'market_closed_today': 'Bugün kapalı',
      'market_open_today': 'Bugün açık',
      'open_days_unknown': 'Açık gün bilgisi yok',
      'find_location': 'Konumunuzu bul',
      'welcome_title': 'Pazaryeri\'ne Hoş Geldiniz',
      'email_label': 'E-posta',
      'password_label': 'Şifre',
      'email_error': 'Lütfen e-posta adresinizi girin.',
      'password_error': 'Lütfen şifrenizi girin.',
      'login_error': 'E-posta veya şifre hatalı.',
      'no_account': 'Hesabınız yok mu? Kayıt Olun',
      'continue_guest': 'Giriş Yapmadan Devam Et',
      'market_open_status': 'Şu an Açık',
      'market_closed_status': 'Şu an Kapalı',
      'occupancy_rate': 'Doluluk Oranı',
      'address_label': 'Adres',
      'open_days_label': 'Açık Günler',
      'products_label': 'Ürünler',
      'general_products': 'Genel pazar ürünleri',
      'get_directions': 'Yol Tarifi Al (Google Haritalar)',
      'reviews_title': 'Yorumlar ve Puanlar',
      'rate_market': 'Pazarı Değerlendir',
      'comment_hint': 'Yorumunuzu buraya yazın...',
      'send_button': 'Gönder',
      'please_rate': 'Lütfen puan verin',
      'please_comment': 'Lütfen yorum yazın',
      'you': 'Siz',
      'today': 'Bugün',
      'search_placeholder': 'Pazar veya satıcı ara...',
      'no_results': 'Sonuç bulunamadı.',
      'filter_open_today': 'Bugün Açık',
      'filter_weekend': 'Hafta Sonu',
      'search_initial_message': 'Arama yapmak için yukarıya yazın.',
      'recent_searches': 'Son Aramalar',
      'clear_history': 'Geçmişi Temizle',
      'favorites_title': 'Favorilerim',
      'no_favorites': 'Henüz favori pazarınız yok.',
      'my_reviews': 'Değerlendirmelerim',
      'my_questions_title': 'Sorularım',
      'my_ratings_title': 'Değerlendirmelerim',
      'no_questions_yet': 'Henüz bir soru sormadınız.',
      'no_ratings_yet': 'Henüz bir değerlendirme yapmadınız.',
      'no_reviews_yet': 'Henüz bir değerlendirme yapılmadı.',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'pick_image_source': 'Fotoğraf Kaynağı',
      'remove_photo': 'Fotoğrafı Kaldır',
      'remove_photo_confirm_title': 'Fotoğrafı Kaldır',
      'remove_photo_confirm_message':
          'Profil fotoğrafınızı kaldırmak istediğinize emin misiniz?',
      'logout_confirmation_title': 'Çıkış Yap',
      'logout_confirmation_message': 'Çıkış yapmak istediğinize emin misiniz?',
      'yes': 'Evet',
      'no': 'Hayır',
      'register_success': 'Hesabınız başarıyla oluşturuldu.',
      'register_success_verify':
          'Hesabınız başarıyla oluşturuldu. Giriş yapabilirsiniz.',
      'forgot_password': 'Şifremi Unuttum',
      'forgot_password_title': 'Şifre Sıfırlama',
      'enter_email_message':
          'Lütfen kayıtlı e-posta adresinizi girin. Size şifre sıfırlama bağlantısı göndereceğiz.',
      'send_code': 'Bağlantı Gönder',
      'enter_code_message':
          'E-posta adresinize gönderilen 6 haneli kodu girin.',
      'verify_code': 'Doğrula',
      'new_password_label': 'Yeni Şifre',
      'reset_password_button': 'Şifreyi Yenile',
      'code_sent': 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
      'invalid_code': 'Geçersiz kod.',
      'password_reset_success':
          'Şifreniz başarıyla yenilendi. Giriş yapabilirsiniz.',
      'password_strength_very_weak': 'Çok Zayıf',
      'password_strength_weak': 'Zayıf',
      'password_strength_medium': 'Orta',
      'password_strength_good': 'İyi',
      'password_strength_strong': 'Güçlü',
      'check_email_timer': 'Lütfen e-postanızı kontrol edin.',
      'resend_available': 'E-posta gelmediyse tekrar gönderebilirsiniz.',
      'user_not_found': 'Bu e-posta adresiyle kayıtlı kullanıcı bulunamadı.',
      'delete_review_title': 'Değerlendirmeyi Sil',
      'delete_review_confirm':
          'Bu değerlendirmeyi silmek istediğinize emin misiniz?',
      'delete_question_title': 'Soruyu Sil',
      'delete_question_confirm': 'Bu soruyu silmek istediğinize emin misiniz?',
      'edit_review_title': 'Değerlendirmeyi Düzenle',
      'edit_question_title': 'Soruyu Düzenle',
      'update': 'Güncelle',
      'edited': 'Düzenlendi',
      'delete_account': 'Hesabımı Sil',
      'delete_account_confirm_title': 'Hesabı Sil',
      'delete_account_confirm_message':
          'Hesabınızı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      'onboarding_title_1': 'Pazarları Keşfet',
      'onboarding_desc_1':
          'Konumuna en yakın semt pazarlarını harita üzerinde gör ve yol tarifi al.',
      'onboarding_title_2': 'Güncel Bilgiler',
      'onboarding_desc_2':
          'Pazarların hangi gün açık olduğunu ve hangi ürünlerin satıldığını öğren.',
      'onboarding_title_3': 'Topluluğa Katıl',
      'onboarding_desc_3':
          'Pazarları değerlendir, yorum yap ve favorilerini kaydet.',
      'skip': 'Atla',
      'next': 'İleri',
      'start': 'Başla',
      'no_internet': 'İnternet bağlantısı yok',
      'theme_settings': 'Tema Ayarları',
      'select_color': 'Tema Rengi',
      'theme_mode': 'Görünüm Modu',
      'light': 'Aydınlık',
      'dark': 'Karanlık',
      'system': 'Sistem Teması',
      'or': 'veya',
      'google_login': 'Google ile Giriş Yap',
      'google_login_error': 'Google girişi başarısız',
      'welcome_dialog_title': 'Aramıza Hoş Geldin!',
      'welcome_dialog_message':
          'Kaydın başarıyla oluşturuldu. Pazaryeri uygulamasını keşfetmeye hemen başla.',
      'seller_panel_title': 'Satıcı Paneli',
      'change_market': 'Pazarı Değiştir',
      'change_market_confirm_title': 'Pazarı Değiştir',
      'change_market_confirm_message':
          'Pazar yerini değiştirmek istediğinize emin misiniz?',
      'select_market_title': 'Pazar Seçimi',
      'select_market_instruction': 'Satış yaptığınız pazarı seçiniz',
      'add_product_tab': 'Ürün Ekle',
      'reviews_tab': 'Değerlendirmeler',
      'product_name_label': 'Ürün Adı',
      'product_price_label': 'Fiyat (₺)',
      'product_desc_label': 'Ürün Açıklaması',
      'stall_location_label': 'Tezgah Tarifi',
      'stall_location_hint': 'Örn: Girişten sağa dönünce 3. tezgah',
      'add_photo_button': 'Fotoğraf Ekle',
      'publish_product_button': 'Ürünü Yayınla',
      'save_and_add_new': 'Kaydet ve Yeni Ekle',
      'questions_title': 'Ürün Soruları',
      'reply_button': 'Yanıtla',
      'answer_hint': 'Yanıtınızı yazın...',
      'success_product_added': 'Ürün başarıyla eklendi!',
      'success_product_deleted': 'Ürün başarıyla silindi.',
      'category_label': 'Kategori Seçiniz',
      'category_fruit': 'Meyve',
      'category_vegetable': 'Sebze',
      'category_delicatessen': 'Şarküteri',
      'category_dairy': 'Süt Ürünleri',
      'category_bakery': 'Unlu Mamuller',
      'category_spices': 'Baharat',
      'category_fish': 'Balık',
      'category_clothing': 'Giyim',
      'category_other': 'Diğer',
      'category_electronics': 'Elektronik',
      'category_second_hand': 'İkinci El',
      'category_animals': 'Canlı Hayvan',
      'category_home': 'Ev & Yaşam',
      'category_toys': 'Oyuncak',
      'category_books': 'Kitap & Kırtasiye',
      'category_tools': 'Hırdavat & Yapı',
      'category_plants': 'Bitki & Çiçek',
      'category_handmade': 'El Emeği',
      'category_cosmetics': 'Kozmetik',
      'category_sports': 'Spor & Outdoor',
      'category_automotive': 'Oto Aksesuar',
      'category_antiques': 'Antika',
      'category_jewelry': 'Takı & Mücevher',
      'category_art': 'Sanat',
      'category_baby': 'Anne & Bebek',
      'category_music': 'Müzik Aletleri',
      'category_office': 'Ofis & Mobilya',
      'category_error': 'Lütfen bir kategori seçin',
      'my_products_tab': 'Ürünlerim',
      'no_products_added': 'Henüz ürün bulunmuyor.',
      'exit_seller_panel': 'Panelden Çık',
      'delete_product_title': 'Ürünü Sil',
      'delete_product_confirm': 'Bu ürünü silmek istediğinize emin misiniz?',
      'edit_product_title': 'Ürünü Düzenle',
      'update_button': 'Güncelle',
      'stock_status_label': 'Stok Durumu',
      'in_stock': 'Stokta Var',
      'out_of_stock': 'Stokta Yok',
      'view_count_label': 'Görüntülenme',
      'filter_all': 'Tümü',
      'filter_read': 'Okunmuş',
      'filter_unread': 'Okunmamış',
      'filter_unanswered': 'Yanıtlanmamış Sorular',
      'filter_by_category': 'Kategoriye Göre Filtrele',
      'filter_by_product': 'Ürüne Göre Filtrele',
      'seller_settings_title': 'Satıcı Ayarları',
      'stall_name_label': 'Tezgah Adı',
      'stall_desc_label': 'Tezgah Açıklaması & Tarifi',
      'stall_hours_label': 'Çalışma Saatleri',
      'stall_hours_hint': 'Örn: 08:00 - 19:00',
      'social_media_title': 'Sosyal Medya',
      'instagram_label': 'Instagram',
      'facebook_label': 'Facebook',
      'save_changes': 'Değişiklikleri Kaydet',
      'success_settings_updated': 'Ayarlar başarıyla güncellendi.',
      'product_stock_active': 'Ürün satışa açıldı.',
      'product_stock_inactive': 'Ürün satışa kapatıldı.',
      'statistics_tab': 'İstatistikler',
      'stats_title': 'Satış İstatistikleri',
      'total_views': 'Toplam Görüntülenme',
      'most_viewed': 'En Çok Görüntülenen',
      'most_sold': 'En Çok Satılan',
      'no_stats_data': 'Henüz istatistik verisi yok.',
      'total_products': 'Toplam Ürün',
      'total_sales': 'Toplam Satış',
      'total_sales_product': 'Toplam Satış (Ürün)',
      'total_revenue': 'Toplam Gelir',
      'critical_stock': 'Tükenmek Üzere',
      'sellers_title': 'Satıcılar',
      'seller_details': 'Satıcı Detayı',
      'seller_products': 'Satıcının Ürünleri',
      'stall_location': 'Tezgah Konumu',
      'no_sellers_found': 'Bu pazarda henüz kayıtlı satıcı bulunmuyor.',
      'product_reviews': 'Ürün Değerlendirmeleri',
      'add_review': 'Değerlendirme Ekle',
      'write_review_hint': 'Ürün hakkında düşünceleriniz...',
      'review_success': 'Değerlendirmeniz başarıyla eklendi.',
      'reply_to_review_title': 'Değerlendirmeyi Yanıtla',
      'seller_reply_label': 'Satıcı Yanıtı',
      'reply_sent_success': 'Yanıt gönderildi.',
      'no_reviews_for_product':
          'Bu ürün için henüz değerlendirme yok. İlk değerlendirmeyi siz yapın!',
      'seller_added_to_favorites': 'Satıcı favorilere eklendi.',
      'seller_removed_from_favorites': 'Satıcı favorilerden çıkarıldı.',
      'favorite_sellers_title': 'Favori Satıcılar',
      'no_favorite_sellers': 'Henüz favori satıcınız yok.',
      'notifications_title': 'Bildirimler',
      'no_notifications': 'Henüz bildiriminiz yok.',
      'mark_all_read': 'Tümünü Okundu İşaretle',
      'phone_verification_title': 'Telefon Doğrulama',
      'enter_sms_code': 'Lütfen telefonunuza gelen 6 haneli kodu girin.',
      'verify_button': 'Doğrula',
      'resend_code': 'Kodu Tekrar Gönder',
      'verification_failed': 'Doğrulama başarısız. Lütfen tekrar deneyin.',
      'account_type_label': 'Hesap Türü',
      'stock_quantity_label': 'Stok Miktarı',
      'unit_label': 'Birim',
      'unit_kg': 'kg',
      'unit_piece': 'Adet',
      'unit_bunch': 'Demet',
      'unit_package': 'Paket',
      'unit_box': 'Koli',
      'low_stock_title': 'Stok Uyarısı',
      'low_stock_message': 'ürününün stoğu azaldı',
      'add_to_cart': 'Sepete Ekle',
      'insufficient_stock': 'Yetersiz Stok',
      'insufficient_stock_message': 'Stokta yeterli ürün yok. Mevcut stok:',
      'added_to_cart_success': 'Ürün sepete eklendi.',
      'connect_with_google': 'Google ile Hesabınızı Bağlayın',
      'report_seller_option': 'Satıcıyı Bildir',
      'report_market_option': 'Pazaryeri\'ni Bildir',
      'select_market_to_report': 'Bildirilecek Pazarı Seçin',
      'select_seller_to_report': 'Bildirilecek Satıcıyı Seçin',
      'report_reason_hint': 'Şikayet/Bildirim detaylarını buraya yazın...',
      'report_sent_success': 'Bildiriminiz başarıyla gönderildi.',
      'report_history': 'Bildirme Geçmişim',
      'no_reports_yet': 'Henüz bir bildirimde bulunmadınız.',
      'report_status_pending': 'İnceleniyor',
      'report_status_reviewed': 'İncelendi',
      'report_status_resolved': 'Çözüldü',
      'personal_information': 'Kişisel Bilgiler',
      'first_name': 'Ad',
      'last_name': 'Soyad',
      'phone_number': 'Telefon Numarası',
      'email': 'E-posta',
      'error_required': 'Bu alan zorunludur',
      'success_profile_updated': 'Profil başarıyla güncellendi',
      'reviews': 'Değerlendirmeler',
      'seller_notifications_tab': 'Satıcı Bildirimleri',
      'marketplace_notifications_tab': 'Pazaryeri',
      'profile_photo_updated': 'Profil fotoğrafı güncellendi',
      'profile_photo_removed': 'Profil fotoğrafı kaldırıldı',
      'email_app_not_found': 'E-posta uygulaması bulunamadı. Adres kopyalandı:',
      'contact_form_title': 'İletişim Formu',
      'subject_suggestion': 'Öneri',
      'subject_complaint': 'Şikayet',
      'subject_bug': 'Hata Bildirimi',
      'subject_support': 'Destek',
      'subject_other': 'Diğer',
      'subject_label': 'Konu',
      'select_hint': 'Seçiniz',
      'message_label': 'Mesajınız',
      'message_hint': 'Mesajınızı buraya yazın...',
      'fill_all_fields': 'Lütfen tüm alanları doldurunuz.',
      'help_support_title': 'Yardım & Destek',
      'app_slogan': 'Semt pazarlarını keşfedin, taze ürünlere ulaşın.',
      'contact_us_title': 'Bize Ulaşın',
      'contact_us_desc': 'Görüş ve önerileriniz için:',
      'create_form_button': 'Form Oluştur',
      'guest_user_title': 'Misafir Kullanıcı',
      'guest_user_subtitle': 'Giriş yapın veya kayıt olun',
      'account_section': 'HESAP',
      'general_section': 'GENEL',
      'login_section': 'GİRİŞ',
      'no_nearby_markets': 'Yakında pazar bulunamadı.',
      'finding_location': 'Konum Bulunuyor...',
      'select_city': 'İl Seçin',
      'select_district': 'İlçe Seçin',
      'no_open_market_found': 'Seçilen günde açık pazar bulunamadı.',
      'day_monday': 'Pazartesi',
      'day_tuesday': 'Salı',
      'day_wednesday': 'Çarşamba',
      'day_thursday': 'Perşembe',
      'day_friday': 'Cuma',
      'day_saturday': 'Cumartesi',
      'day_sunday': 'Pazar',
      'filter_sort_title': 'Filtrele & Sırala',
      'clear_button': 'Temizle',
      'sort_title': 'Sıralama',
      'sort_smart': 'Önerilen',
      'sort_newest': 'En Yeni',
      'sort_oldest': 'En Eski',
      'sort_price_asc': 'Fiyat Artan',
      'sort_price_desc': 'Fiyat Azalan',
      'sort_rating_high': 'Puan (Yüksek)',
      'sort_rating_low': 'Puan (Düşük)',
      'categories_title': 'Kategoriler',
      'price_range_title': 'Fiyat Aralığı',
      'filter_open_today_only': 'Sadece Bugün Açık Olanlar',
      'show_results_button': 'Sonuçları Göster',
      'no_products_found_filter': 'Arama kriterlerinize uygun ürün bulunamadı.',
      'clear_filters_button': 'Filtreleri Temizle',
      'average_working_hours': 'Ortalama Çalışma Saatleri',
      'working_hours_value': '05.00 - 20.00',
      'hourly_occupancy_title': 'Saatlik Yoğunluk Tahmini',
      'hourly_occupancy_desc':
          'Veriler geçmiş ziyaretçi yoğunluğuna göre tahmin edilmiştir.',
      'occupancy_low': 'Tenha',
      'occupancy_low_desc': 'Alışveriş için en uygun zaman.',
      'occupancy_medium': 'Normal',
      'occupancy_medium_desc': 'Pazar yeri hareketli.',
      'occupancy_high': 'Kalabalık',
      'occupancy_high_desc': 'Pazar yeri oldukça yoğun.',
      'current_occupancy_title': 'Anlık Doluluk Durumu',
      'report_presence_button': 'Ben Buradayım (Yoğunluk Bildir)',
      'presence_reported_button': 'Bildiriminiz Alındı',
      'presence_reported_success': 'Bildiriminiz alındı, teşekkürler!',
      'see_all_reviews': 'Tüm Değerlendirmeleri Gör',
      'existing_photo_hint':
          'Mevcut fotoğraf. Değiştirmek için aşağıdan yeni fotoğraf seçiniz.',
      'min_3_chars_error': 'En az 3 karakter giriniz',
      'add_photo_error': 'Lütfen en az bir ürün fotoğrafı ekleyin.',
      'fill_all_fields_error': 'Lütfen tüm alanları eksiksiz doldurunuz.',
      'seller_default_name': 'Satıcı',
      'deleted_product': 'Silinmiş Ürün',
      'no_product_info': 'Ürün Bilgisi Yok',
      'other_sellers_title': 'Bu Ürünü Satan Diğer Satıcılar',
      'more_sellers_button': 'Satıcıda Daha Var - Fiyatları Gör',
      'ask_question_title': 'Soru Sor',
      'question_hint': 'Sorunuzu buraya yazın...',
      'question_sent_success': 'Sorunuz başarıyla gönderildi.',
      'market_sellers_title': 'Pazardaki Satıcılar',
      'no_sellers_found_simple': 'Satıcı bulunamadı.',
      'no_similar_products': 'Benzer ürün bulunamadı.',
      'see_all_questions': 'Tüm Soruları Gör',
      'no_questions_yet_simple': 'Henüz soru sorulmamış.',
      'selected_count_suffix': 'Seçildi',
      'delete_selected_title': 'Seçilenleri Sil',
      'delete_selected_confirm_suffix':
          'bildirimi silmek istediğinize emin misiniz?',
      'delete_notification_title': 'Bildirimi Sil',
      'delete_notification_confirm':
          'Bu bildirimi silmek istediğinize emin misiniz?',
      'view_product_button': 'Ürünü Görüntüle',
      'view_question_button': 'Soruyu Gör',
      'view_review_button': 'Yorumu Gör',
      'view_reply_button': 'Cevabı Gör',
      'close_button': 'Kapat',
      'question_detail_title': 'Soru Detayı',
      'review_detail_title': 'Değerlendirme Detayı',
      'product_not_found_error': 'Ürün bulunamadı veya silinmiş.',
      'generic_error': 'Bir hata oluştu.',
      'questions_tab': 'Sorular',
      'reviews_tab_short': 'Değerlendirme',
      'select_city_all': 'İl Seçiniz (Tümü)',
      'all_option': 'Tümü',
      'search_market_hint': 'Pazar Ara...',
      'stock_distribution_title': 'Stok Durumu Dağılımı',
      'stock_high': 'Yüksek',
      'stock_low': 'Düşük',
      'stock_out': 'Tükendi',
      'legend_stock_high': 'Yüksek Stok (>20)',
      'legend_stock_low': 'Düşük Stok (1-20)',
      'legend_stock_out': 'Tükendi (0)',
      'recent_viewers_title': 'Son Görüntüleyenler',
      'no_viewers_yet': 'Henüz görüntüleyen yok.',
      'viewed_suffix': 'görüntülendi',
      'no_sales_chart_data': 'Henüz satış verisi grafiği oluşmadı.',
      'product_list_title': 'Ürün Listesi',
      'revenue_calculation_title': 'Gelir Hesaplaması',
      'no_sales_revenue_yet': 'Henüz satış geliri yok.',
      'pieces_x': 'adet x',
      'total_label': 'Toplam',
      'slide_to_adjust_color': 'Rengi ayarlamak için kaydırın',
      'quick_select_title': 'Hızlı Seçim',
      'market_tab': 'Pazar',
      'seller_tab': 'Satıcı',
      'connection_restored': 'Bağlantı sağlandı',
    },
    'en': {
      'report_seller_option': 'Report Seller',
      'report_market_option': 'Report Market',
      'select_market_to_report': 'Select Market to Report',
      'select_seller_to_report': 'Select Seller to Report',
      'report_reason_hint': 'Write complaint/report details here...',
      'report_sent_success': 'Your report has been sent successfully.',
      'report_history': 'My Report History',
      'no_reports_yet': 'You haven\'t submitted any reports yet.',
      'report_status_pending': 'Pending',
      'report_status_reviewed': 'Reviewed',
      'report_status_resolved': 'Resolved',
      'home_title': 'MARKETPLACE',
      'account_title': 'MY ACCOUNT',
      'personal_information': 'Personal Information',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone_number': 'Phone Number',
      'email': 'Email',
      'error_required': 'This field is required',
      'success_profile_updated': 'Profile updated successfully',
      'seller_notifications_tab': 'Seller Notifications',
      'marketplace_notifications_tab': 'Marketplace',
      'login': 'Login',
      'login_success': 'Login successful. Welcome!',
      'logout': 'Logout',
      'register': 'Register',
      'dark_mode': 'Dark Mode',
      'language': 'Language / Dil',
      'welcome': 'Welcome',
      'guest_login_success': 'Logged in as guest.',
      'guest_message':
          'Please login to view your account details and enjoy personal benefits.',
      'edit_profile': 'Edit Profile',
      'create_account': 'Create Account',
      'search_hint': 'Search product (e.g. apple)',
      'nearby_markets': 'Nearby Street Markets',
      'see_all': 'See All',
      'all_markets': 'All Markets',
      'settings': 'Settings',
      'location_refresh': 'Refresh Location',
      'customer_label': 'Customer',
      'seller_label': 'Seller',
      'select_user_type': 'Select User Type',
      'seller_login': 'Seller Login',
      'email_not_verified_message':
          'Your email address is not verified. Please check your inbox.',
      'resend_verification_email': 'Resend Verification Email',
      'verification_email_sent_success': 'Verification email sent again.',
      'cancel': 'Cancel',
      'remember_me': 'Remember Me',
      'search_tab': 'SEARCH',
      'products_tab': 'PRODUCTS',
      'report_tab': 'REPORT',
      'logout_success': 'Logged out successfully.',
      'location_title': 'Exact Location',
      'city': 'City',
      'coordinate': 'Coordinate',
      'location_updated': 'Location updated',
      'markets_loaded': 'markets loaded',
      'unknown': 'unknown',
      'selected_province': 'Selected province',
      'search_province_hint': 'Search province (e.g. Ist)',
      'clear_selection': 'Clear Selection',
      'error_prefix': 'Error',
      'location_settings': 'Location settings',
      'retry': 'Retry',
      'province_not_found': 'No markets found for province',
      'market_closed_today': 'Closed today',
      'market_open_today': 'Open today',
      'open_days_unknown': 'Open days unknown',
      'find_location': 'Find your location',
      'welcome_title': 'Welcome to Marketplace',
      'email_label': 'Email',
      'password_label': 'Password',
      'email_error': 'Please enter your email.',
      'password_error': 'Please enter your password.',
      'login_error': 'Incorrect email or password.',
      'no_account': 'Don\'t have an account? Register',
      'continue_guest': 'Continue without Login',
      'market_open_status': 'Open Now',
      'market_closed_status': 'Closed Now',
      'occupancy_rate': 'Occupancy Rate',
      'address_label': 'Address',
      'open_days_label': 'Open Days',
      'products_label': 'Products',
      'general_products': 'General market products',
      'get_directions': 'Get Directions (Google Maps)',
      'reviews_title': 'Reviews and Ratings',
      'rate_market': 'Rate Market',
      'comment_hint': 'Write your comment here...',
      'send_button': 'Send',
      'please_rate': 'Please rate',
      'please_comment': 'Please write a comment',
      'you': 'You',
      'today': 'Today',
      'search_placeholder': 'Search market, district or product...',
      'no_results': 'No results found.',
      'filter_open_today': 'Open Today',
      'filter_weekend': 'Weekend',
      'search_initial_message': 'Type above to search.',
      'recent_searches': 'Recent Searches',
      'clear_history': 'Clear History',
      'favorites_title': 'My Favorites',
      'no_favorites': 'No favorite markets yet.',
      'my_reviews': 'My Reviews',
      'my_questions_title': 'My Questions',
      'my_ratings_title': 'My Ratings',
      'no_questions_yet': 'You haven\'t asked any questions yet.',
      'no_ratings_yet': 'You haven\'t made any ratings yet.',
      'no_reviews_yet': 'You haven\'t posted any reviews yet.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pick_image_source': 'Image Source',
      'remove_photo': 'Remove Photo',
      'remove_photo_confirm_title': 'Remove Photo',
      'remove_photo_confirm_message':
          'Are you sure you want to remove your profile photo?',
      'logout_confirmation_title': 'Logout',
      'logout_confirmation_message': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'register_success': 'Account created successfully.',
      'register_success_verify':
          'Account created successfully. You can now login.',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'enter_email_message':
          'Please enter your registered email address. We will send you a password reset link.',
      'send_code': 'Send Link',
      'enter_code_message': 'Enter the 6-digit code sent to your email.',
      'verify_code': 'Verify',
      'new_password_label': 'New Password',
      'reset_password_button': 'Reset Password',
      'code_sent': 'Password reset link sent to your email.',
      'invalid_code': 'Invalid code.',
      'password_reset_success':
          'Password reset successfully. You can now login.',
      'password_strength_very_weak': 'Very Weak',
      'password_strength_weak': 'Weak',
      'password_strength_medium': 'Medium',
      'password_strength_good': 'Good',
      'password_strength_strong': 'Strong',
      'check_email_timer': 'Please check your email.',
      'resend_available': 'If email not received, you can resend.',
      'user_not_found': 'No user found with this email address.',
      'delete_review_title': 'Delete Review',
      'delete_review_confirm': 'Are you sure you want to delete this review?',
      'delete_question_title': 'Delete Question',
      'delete_question_confirm':
          'Are you sure you want to delete this question?',
      'edit_review_title': 'Edit Review',
      'edit_question_title': 'Edit Question',
      'update': 'Update',
      'edited': 'Edited',
      'delete_account': 'Delete Account',
      'delete_account_confirm_title': 'Delete Account',
      'delete_account_confirm_message':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'onboarding_title_1': 'Discover Markets',
      'onboarding_desc_1':
          'Find the nearest street markets on the map and get directions.',
      'onboarding_title_2': 'Up-to-date Info',
      'onboarding_desc_2':
          'Learn which days markets are open and what products are sold.',
      'onboarding_title_3': 'Join the Community',
      'onboarding_desc_3':
          'Rate markets, leave comments and save your favorites.',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Start',
      'no_internet': 'No internet connection',
      'theme_settings': 'Theme Settings',
      'select_color': 'Theme Color',
      'theme_mode': 'Appearance Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System Theme',
      'or': 'or',
      'google_login': 'Sign in with Google',
      'google_login_error': 'Google sign in failed',
      'welcome_dialog_title': 'Welcome Aboard!',
      'welcome_dialog_message':
          'Your account has been successfully created. Start exploring Marketplace now.',
      'seller_panel_title': 'Seller Panel',
      'change_market': 'Change Market',
      'change_market_confirm_title': 'Change Market',
      'change_market_confirm_message':
          'Are you sure you want to change the market?',
      'select_market_title': 'Select Market',
      'select_market_instruction': 'Select the market you are selling at',
      'add_product_tab': 'Add Product',
      'reviews_tab': 'Reviews',
      'product_name_label': 'Product Name',
      'product_price_label': 'Price (₺)',
      'product_desc_label': 'Product Description',
      'stall_location_label': 'Stall Location',
      'stall_location_hint': 'e.g. 3rd stall after turning right at entrance',
      'add_photo_button': 'Add Photo',
      'publish_product_button': 'Publish Product',
      'save_and_add_new': 'Save and Add New',
      'questions_title': 'Product Questions',
      'reply_button': 'Reply',
      'answer_hint': 'Write your answer...',
      'success_product_added': 'Product added successfully!',
      'success_product_deleted': 'Product deleted successfully.',
      'category_label': 'Select Category',
      'category_fruit': 'Fruit',
      'category_vegetable': 'Vegetable',
      'category_delicatessen': 'Delicatessen',
      'category_dairy': 'Dairy',
      'category_bakery': 'Bakery',
      'category_spices': 'Spices',
      'category_fish': 'Fish',
      'category_clothing': 'Clothing',
      'category_other': 'Other',
      'category_electronics': 'Electronics',
      'category_second_hand': 'Second Hand',
      'category_animals': 'Pet Supplies',
      'category_home': 'Home & Living',
      'category_toys': 'Toys',
      'category_books': 'Books & Stationery',
      'category_tools': 'Hardware & Tools',
      'category_plants': 'Plants & Flowers',
      'category_handmade': 'Handmade',
      'category_cosmetics': 'Cosmetics',
      'category_sports': 'Sports & Outdoor',
      'category_automotive': 'Automotive',
      'category_antiques': 'Antiques',
      'category_jewelry': 'Jewelry',
      'category_art': 'Art',
      'category_baby': 'Mother & Baby',
      'category_music': 'Music',
      'category_office': 'Office & Furniture',
      'category_error': 'Please select a category',
      'my_products_tab': 'My Products',
      'no_products_added': 'No products added yet.',
      'exit_seller_panel': 'Exit Panel',
      'delete_product_title': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete this product?',
      'edit_product_title': 'Edit Product',
      'update_button': 'Update',
      'stock_status_label': 'Stock Status',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'view_count_label': 'Views',
      'filter_all': 'All',
      'filter_read': 'Read',
      'filter_unread': 'Unread',
      'filter_unanswered': 'Unanswered Questions',
      'filter_by_category': 'Filter by Category',
      'filter_by_product': 'Filter by Product',
      'seller_settings_title': 'Seller Settings',
      'stall_name_label': 'Stall Name',
      'stall_desc_label': 'Stall Description',
      'stall_hours_label': 'Working Hours',
      'stall_hours_hint': 'e.g. 08:00 - 19:00',
      'social_media_title': 'Social Media',
      'instagram_label': 'Instagram',
      'facebook_label': 'Facebook',
      'save_changes': 'Save Changes',
      'success_settings_updated': 'Settings updated successfully.',
      'product_stock_active': 'Product is now on sale.',
      'product_stock_inactive': 'Product is no longer on sale.',
      'statistics_tab': 'Statistics',
      'stats_title': 'Sales Statistics',
      'total_views': 'Total Views',
      'most_viewed': 'Most Viewed',
      'most_sold': 'Most Sold',
      'no_stats_data': 'No statistics data yet.',
      'total_products': 'Total Products',
      'total_sales': 'Total Sales',
      'total_sales_product': 'Total Sales (Product)',
      'total_revenue': 'Total Revenue',
      'critical_stock': 'Running Low',
      'sellers_title': 'Sellers',
      'seller_details': 'Seller Details',
      'seller_products': 'Seller\'s Products',
      'stall_location': 'Stall Location',
      'no_sellers_found': 'No registered sellers found in this market yet.',
      'product_reviews': 'Product Reviews',
      'add_review': 'Add Review',
      'write_review_hint': 'Your thoughts about the product...',
      'review_success': 'Review added successfully.',
      'reply_to_review_title': 'Reply to Review',
      'seller_reply_label': 'Seller Reply',
      'reply_sent_success': 'Reply sent.',
      'no_reviews_for_product':
          'No reviews for this product yet. Be the first to review!',
      'seller_added_to_favorites': 'Seller added to favorites.',
      'seller_removed_from_favorites': 'Seller removed from favorites.',
      'favorite_sellers_title': 'Favorite Sellers',
      'no_favorite_sellers': 'No favorite sellers yet.',
      'notifications_title': 'Notifications',
      'no_notifications': 'No notifications yet.',
      'mark_all_read': 'Mark All as Read',
      'phone_verification_title': 'Phone Verification',
      'enter_sms_code': 'Please enter the 6-digit code sent to your phone.',
      'verify_button': 'Verify',
      'resend_code': 'Resend Code',
      'verification_failed': 'Verification failed. Please try again.',
      'account_type_label': 'Account Type',
      'stock_quantity_label': 'Stock Quantity',
      'unit_label': 'Unit',
      'unit_kg': 'kg',
      'unit_piece': 'Piece',
      'unit_bunch': 'Bunch',
      'unit_package': 'Package',
      'unit_box': 'Box',
      'low_stock_title': 'Stock Warning',
      'low_stock_message': 'stock is low',
      'add_to_cart': 'Add to Cart',
      'insufficient_stock': 'Insufficient Stock',
      'insufficient_stock_message': 'Not enough stock. Available:',
      'added_to_cart_success': 'Product added to cart.',
      'connect_with_google': 'Connect your account with Google',
      'profile_photo_updated': 'Profile photo updated',
      'profile_photo_removed': 'Profile photo removed',
      'email_app_not_found': 'Email app not found. Address copied:',
      'contact_form_title': 'Contact Form',
      'subject_suggestion': 'Suggestion',
      'subject_complaint': 'Complaint',
      'subject_bug': 'Bug Report',
      'subject_support': 'Support',
      'subject_other': 'Other',
      'subject_label': 'Subject',
      'select_hint': 'Select',
      'message_label': 'Your Message',
      'message_hint': 'Type your message here...',
      'fill_all_fields': 'Please fill in all fields.',
      'help_support_title': 'Help & Support',
      'app_slogan': 'Discover street markets, reach fresh products.',
      'contact_us_title': 'Contact Us',
      'contact_us_desc': 'For your feedback and suggestions:',
      'create_form_button': 'Create Form',
      'guest_user_title': 'Guest User',
      'guest_user_subtitle': 'Login or register',
      'account_section': 'ACCOUNT',
      'general_section': 'GENERAL',
      'login_section': 'LOGIN',
      'no_nearby_markets': 'No nearby markets found.',
      'finding_location': 'Finding Location...',
      'select_city': 'Select City',
      'select_district': 'Select District',
      'no_open_market_found': 'No open market found on selected day.',
      'day_monday': 'Monday',
      'day_tuesday': 'Tuesday',
      'day_wednesday': 'Wednesday',
      'day_thursday': 'Thursday',
      'day_friday': 'Friday',
      'day_saturday': 'Saturday',
      'day_sunday': 'Sunday',
      'filter_sort_title': 'Filter & Sort',
      'clear_button': 'Clear',
      'sort_title': 'Sort By',
      'sort_smart': 'Recommended',
      'sort_newest': 'Newest',
      'sort_oldest': 'Oldest',
      'sort_price_asc': 'Price Low to High',
      'sort_price_desc': 'Price High to Low',
      'sort_rating_high': 'Rating (High)',
      'sort_rating_low': 'Rating (Low)',
      'categories_title': 'Categories',
      'price_range_title': 'Price Range',
      'filter_open_today_only': 'Open Today Only',
      'show_results_button': 'Show Results',
      'no_products_found_filter': 'No products found matching your criteria.',
      'clear_filters_button': 'Clear Filters',
      'average_working_hours': 'Average Working Hours',
      'working_hours_value': '05.00 - 20.00',
      'hourly_occupancy_title': 'Hourly Occupancy Forecast',
      'hourly_occupancy_desc':
          'Data is estimated based on past visitor density.',
      'occupancy_low': 'Quiet',
      'occupancy_low_desc': 'Best time for shopping.',
      'occupancy_medium': 'Normal',
      'occupancy_medium_desc': 'Market is active.',
      'occupancy_high': 'Crowded',
      'occupancy_high_desc': 'Market is very busy.',
      'current_occupancy_title': 'Live Occupancy Status',
      'report_presence_button': 'I\'m Here (Report Density)',
      'presence_reported_button': 'Report Received',
      'presence_reported_success': 'Your report has been received, thanks!',
      'see_all_reviews': 'See All Reviews',
      'existing_photo_hint':
          'Current photo. Select a new photo below to change.',
      'min_3_chars_error': 'Enter at least 3 characters',
      'add_photo_error': 'Please add at least one product photo.',
      'fill_all_fields_error': 'Please fill in all fields completely.',
      'seller_default_name': 'Seller',
      'deleted_product': 'Deleted Product',
      'no_product_info': 'No Product Info',
      'other_sellers_title': 'Other Sellers Selling This Product',
      'more_sellers_button': 'Available at more sellers - See Prices',
      'ask_question_title': 'Ask a Question',
      'question_hint': 'Type your question here...',
      'question_sent_success': 'Your question has been sent successfully.',
      'market_sellers_title': 'Sellers in Market',
      'no_sellers_found_simple': 'No sellers found.',
      'no_similar_products': 'No similar products found.',
      'see_all_questions': 'See All Questions',
      'no_questions_yet_simple': 'No questions asked yet.',
      'selected_count_suffix': 'Selected',
      'delete_selected_title': 'Delete Selected',
      'delete_selected_confirm_suffix':
          'notifications? This action cannot be undone.',
      'delete_notification_title': 'Delete Notification',
      'delete_notification_confirm':
          'Are you sure you want to delete this notification?',
      'view_product_button': 'View Product',
      'view_question_button': 'View Question',
      'view_review_button': 'View Review',
      'view_reply_button': 'View Reply',
      'close_button': 'Close',
      'question_detail_title': 'Question Detail',
      'review_detail_title': 'Review Detail',
      'product_not_found_error': 'Product not found or deleted.',
      'generic_error': 'An error occurred.',
      'questions_tab': 'Questions',
      'reviews_tab_short': 'Reviews',
      'select_city_all': 'Select City (All)',
      'all_option': 'All',
      'search_market_hint': 'Search Market...',
      'stock_distribution_title': 'Stock Distribution',
      'stock_high': 'High',
      'stock_low': 'Low',
      'stock_out': 'Out of Stock',
      'legend_stock_high': 'High Stock (>20)',
      'legend_stock_low': 'Low Stock (1-20)',
      'legend_stock_out': 'Out of Stock (0)',
      'recent_viewers_title': 'Recent Viewers',
      'no_viewers_yet': 'No viewers yet.',
      'viewed_suffix': 'viewed',
      'no_sales_chart_data': 'Sales chart data not generated yet.',
      'product_list_title': 'Product List',
      'revenue_calculation_title': 'Revenue Calculation',
      'no_sales_revenue_yet': 'No sales revenue yet.',
      'pieces_x': 'pcs x',
      'total_label': 'Total',
      'slide_to_adjust_color': 'Slide to adjust color',
      'quick_select_title': 'Quick Select',
      'market_tab': 'Market',
      'seller_tab': 'Seller',
      'connection_restored': 'Connection restored',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
