class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'home_title': 'PAZARYERİ',
      'account_title': 'HESABIM',
      'login': 'Giriş Yap',
      'logout': 'Çıkış Yap',
      'register': 'Kayıt Ol',
      'dark_mode': 'Karanlık Mod',
      'language': 'Dil / Language',
      'welcome': 'Hoş geldin',
      'guest_message':
          'Hesabım alanını görüntülemek ve kişisel avantajlardan yararlanmak için lütfen giriş yapın.',
      'edit_profile': 'Profili Düzenle',
      'create_account': 'Hesap Oluştur',
      'search_hint': 'Ürün ara (ör: elma)',
      'nearby_markets': 'En Yakın Semt Pazarları',
      'all_markets': 'Tüm Pazarlar',
      'settings': 'Ayarlar',
      'location_refresh': 'Konumu Yenile',
      'search_tab': 'ARA',
      'report_tab': 'BİLDİR',
      'logout_success': 'Oturum kapatıldı.',
      'location_title': 'Tam Konum',
      'city': 'Şehir',
      'coordinate': 'Koordinat',
      'location_updated': 'Konum güncellendi',
      'markets_loaded': 'pazar yüklendi',
      'unknown': 'bilinmiyor',
      'selected_province': 'Seçilen il',
      'search_province_hint': 'İl ara (örn: İst veya An)',
      'clear_selection': 'Seçimi Temizle',
      'error_prefix': 'Hata',
      'location_settings': 'Konum ayarları',
      'retry': 'Yeniden Dene',
      'province_not_found': 'iline ait pazar bulunamadı.',
      'market_closed_today': 'Bugün kapalı',
      'market_open_today': 'Bugün açık',
      'open_days_unknown': 'Açık gün bilgisi yok',
      'find_location': 'Konumunuzu bul',
      'welcome_title': 'Pazaryeri\'ne Hoş Geldiniz',
      'email_label': 'E-posta',
      'password_label': 'Şifre',
      'email_error': 'Lütfen e-posta adresinizi girin.',
      'password_error': 'Lütfen şifrenizi girin.',
      'login_error': 'E-posta veya şifre hatalı.',
      'no_account': 'Hesabınız yok mu? Kayıt Olun',
      'continue_guest': 'Giriş Yapmadan Devam Et',
      'market_open_status': 'Şu an Açık',
      'market_closed_status': 'Şu an Kapalı',
      'address_label': 'Adres',
      'open_days_label': 'Açık Günler',
      'products_label': 'Ürünler',
      'general_products': 'Genel pazar ürünleri',
      'get_directions': 'Yol Tarifi Al (Google Haritalar)',
      'reviews_title': 'Yorumlar ve Puanlar',
      'rate_market': 'Pazarı Değerlendir',
      'comment_hint': 'Yorumunuzu buraya yazın...',
      'send_button': 'Gönder',
      'please_rate': 'Lütfen puan verin',
      'please_comment': 'Lütfen yorum yazın',
      'you': 'Siz',
      'today': 'Bugün',
      'search_placeholder': 'Pazar, ilçe veya ürün ara...',
      'no_results': 'Sonuç bulunamadı.',
      'filter_open_today': 'Bugün Açık',
      'filter_weekend': 'Hafta Sonu',
      'search_initial_message': 'Arama yapmak için yukarıya yazın.',
      'recent_searches': 'Son Aramalar',
      'clear_history': 'Geçmişi Temizle',
      'favorites_title': 'Favorilerim',
      'no_favorites': 'Henüz favori pazarınız yok.',
      'my_reviews': 'Yorumlarım',
      'no_reviews_yet': 'Henüz bir yorum yapmadınız.',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'pick_image_source': 'Fotoğraf Kaynağı',
      'remove_photo': 'Fotoğrafı Kaldır',
      'logout_confirmation_title': 'Çıkış Yap',
      'logout_confirmation_message': 'Çıkış yapmak istediğinize emin misiniz?',
      'yes': 'Evet',
      'no': 'Hayır',
      'forgot_password': 'Şifremi Unuttum',
      'forgot_password_title': 'Şifre Sıfırlama',
      'enter_email_message':
          'Lütfen kayıtlı e-posta adresinizi girin. Size bir doğrulama kodu göndereceğiz.',
      'send_code': 'Kod Gönder',
      'enter_code_message':
          'E-posta adresinize gönderilen 6 haneli kodu girin.',
      'verify_code': 'Doğrula',
      'new_password_label': 'Yeni Şifre',
      'reset_password_button': 'Şifreyi Yenile',
      'code_sent': 'Doğrulama kodu gönderildi: 123456',
      'invalid_code': 'Geçersiz kod.',
      'password_reset_success':
          'Şifreniz başarıyla yenilendi. Giriş yapabilirsiniz.',
      'user_not_found': 'Bu e-posta adresiyle kayıtlı kullanıcı bulunamadı.',
      'delete_review_title': 'Yorumu Sil',
      'delete_review_confirm': 'Bu yorumu silmek istediğinize emin misiniz?',
      'delete_account': 'Hesabımı Sil',
      'delete_account_confirm_title': 'Hesabı Sil',
      'delete_account_confirm_message':
          'Hesabınızı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      'onboarding_title_1': 'Pazarları Keşfet',
      'onboarding_desc_1':
          'Konumuna en yakın semt pazarlarını harita üzerinde gör ve yol tarifi al.',
      'onboarding_title_2': 'Güncel Bilgiler',
      'onboarding_desc_2':
          'Pazarların hangi gün açık olduğunu ve hangi ürünlerin satıldığını öğren.',
      'onboarding_title_3': 'Topluluğa Katıl',
      'onboarding_desc_3':
          'Pazarları değerlendir, yorum yap ve favorilerini kaydet.',
      'skip': 'Atla',
      'next': 'İleri',
      'start': 'Başla',
      'no_internet': 'İnternet bağlantısı yok',
      'theme_settings': 'Tema Ayarları',
      'select_color': 'Tema Rengi',
      'theme_mode': 'Görünüm Modu',
      'light': 'Aydınlık',
      'dark': 'Karanlık',
    },
    'en': {
      'home_title': 'MARKETPLACE',
      'account_title': 'MY ACCOUNT',
      'login': 'Login',
      'logout': 'Logout',
      'register': 'Register',
      'dark_mode': 'Dark Mode',
      'language': 'Language / Dil',
      'welcome': 'Welcome',
      'guest_message':
          'Please login to view your account details and enjoy personal benefits.',
      'edit_profile': 'Edit Profile',
      'create_account': 'Create Account',
      'search_hint': 'Search product (e.g. apple)',
      'nearby_markets': 'Nearby Street Markets',
      'all_markets': 'All Markets',
      'settings': 'Settings',
      'location_refresh': 'Refresh Location',
      'search_tab': 'SEARCH',
      'report_tab': 'REPORT',
      'logout_success': 'Logged out successfully.',
      'location_title': 'Exact Location',
      'city': 'City',
      'coordinate': 'Coordinate',
      'location_updated': 'Location updated',
      'markets_loaded': 'markets loaded',
      'unknown': 'unknown',
      'selected_province': 'Selected province',
      'search_province_hint': 'Search province (e.g. Ist)',
      'clear_selection': 'Clear Selection',
      'error_prefix': 'Error',
      'location_settings': 'Location settings',
      'retry': 'Retry',
      'province_not_found': 'No markets found for province',
      'market_closed_today': 'Closed today',
      'market_open_today': 'Open today',
      'open_days_unknown': 'Open days unknown',
      'find_location': 'Find your location',
      'welcome_title': 'Welcome to Marketplace',
      'email_label': 'Email',
      'password_label': 'Password',
      'email_error': 'Please enter your email.',
      'password_error': 'Please enter your password.',
      'login_error': 'Incorrect email or password.',
      'no_account': 'Don\'t have an account? Register',
      'continue_guest': 'Continue without Login',
      'market_open_status': 'Open Now',
      'market_closed_status': 'Closed Now',
      'address_label': 'Address',
      'open_days_label': 'Open Days',
      'products_label': 'Products',
      'general_products': 'General market products',
      'get_directions': 'Get Directions (Google Maps)',
      'reviews_title': 'Reviews and Ratings',
      'rate_market': 'Rate Market',
      'comment_hint': 'Write your comment here...',
      'send_button': 'Send',
      'please_rate': 'Please rate',
      'please_comment': 'Please write a comment',
      'you': 'You',
      'today': 'Today',
      'search_placeholder': 'Search market, district or product...',
      'no_results': 'No results found.',
      'filter_open_today': 'Open Today',
      'filter_weekend': 'Weekend',
      'search_initial_message': 'Type above to search.',
      'recent_searches': 'Recent Searches',
      'clear_history': 'Clear History',
      'favorites_title': 'My Favorites',
      'no_favorites': 'No favorite markets yet.',
      'my_reviews': 'My Reviews',
      'no_reviews_yet': 'You haven\'t posted any reviews yet.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pick_image_source': 'Image Source',
      'remove_photo': 'Remove Photo',
      'logout_confirmation_title': 'Logout',
      'logout_confirmation_message': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'enter_email_message':
          'Please enter your registered email address. We will send you a verification code.',
      'send_code': 'Send Code',
      'enter_code_message': 'Enter the 6-digit code sent to your email.',
      'verify_code': 'Verify',
      'new_password_label': 'New Password',
      'reset_password_button': 'Reset Password',
      'code_sent': 'Verification code sent: 123456',
      'invalid_code': 'Invalid code.',
      'password_reset_success':
          'Password reset successfully. You can now login.',
      'user_not_found': 'No user found with this email address.',
      'delete_review_title': 'Delete Review',
      'delete_review_confirm': 'Are you sure you want to delete this review?',
      'delete_account': 'Delete Account',
      'delete_account_confirm_title': 'Delete Account',
      'delete_account_confirm_message':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'onboarding_title_1': 'Discover Markets',
      'onboarding_desc_1':
          'Find the nearest street markets on the map and get directions.',
      'onboarding_title_2': 'Up-to-date Info',
      'onboarding_desc_2':
          'Learn which days markets are open and what products are sold.',
      'onboarding_title_3': 'Join the Community',
      'onboarding_desc_3':
          'Rate markets, leave comments and save your favorites.',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Start',
      'no_internet': 'No internet connection',
      'theme_settings': 'Theme Settings',
      'select_color': 'Theme Color',
      'theme_mode': 'Appearance Mode',
      'light': 'Light',
      'dark': 'Dark',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
