class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'home_title': 'PAZARYERİ',
      'account_title': 'HESABIM',
      'login': 'Giriş Yap',
      'logout': 'Çıkış Yap',
      'register': 'Kayıt Ol',
      'dark_mode': 'Karanlık Mod',
      'language': 'Dil / Language',
      'welcome': 'Hoş geldin',
      'guest_message':
          'Hesabım alanını görüntülemek ve kişisel avantajlardan yararlanmak için lütfen giriş yapın.',
      'edit_profile': 'Profili Düzenle',
      'create_account': 'Hesap Oluştur',
      'search_hint': 'Ürün ara (ör: elma)',
      'nearby_markets': 'En Yakın Semt Pazarları',
      'all_markets': 'Tüm Pazarlar',
      'settings': 'Ayarlar',
      'location_refresh': 'Konumu Yenile',
      'customer_label': 'Müşteri',
      'seller_label': 'Satıcı',
      'select_user_type': 'Giriş Türü Seçin',
      'seller_login': 'Satıcı Girişi',
      'email_not_verified_message':
          'E-posta adresiniz doğrulanmamış. Lütfen gelen kutunuzu kontrol edin.',
      'resend_verification_email': 'Doğrulama E-postasını Tekrar Gönder',
      'verification_email_sent_success':
          'Doğrulama e-postası tekrar gönderildi.',
      'cancel': 'İptal',
      'remember_me': 'Beni Hatırla',
      'search_tab': 'ARA',
      'report_tab': 'BİLDİR',
      'logout_success': 'Oturum kapatıldı.',
      'location_title': 'Tam Konum',
      'city': 'Şehir',
      'coordinate': 'Koordinat',
      'location_updated': 'Konum güncellendi',
      'markets_loaded': 'pazar yüklendi',
      'unknown': 'bilinmiyor',
      'selected_province': 'Seçilen il',
      'search_province_hint': 'İl ara (örn: İst veya An)',
      'clear_selection': 'Seçimi Temizle',
      'error_prefix': 'Hata',
      'location_settings': 'Konum ayarları',
      'retry': 'Yeniden Dene',
      'province_not_found': 'iline ait pazar bulunamadı.',
      'market_closed_today': 'Bugün kapalı',
      'market_open_today': 'Bugün açık',
      'open_days_unknown': 'Açık gün bilgisi yok',
      'find_location': 'Konumunuzu bul',
      'welcome_title': 'Pazaryeri\'ne Hoş Geldiniz',
      'email_label': 'E-posta',
      'password_label': 'Şifre',
      'email_error': 'Lütfen e-posta adresinizi girin.',
      'password_error': 'Lütfen şifrenizi girin.',
      'login_error': 'E-posta veya şifre hatalı.',
      'no_account': 'Hesabınız yok mu? Kayıt Olun',
      'continue_guest': 'Giriş Yapmadan Devam Et',
      'market_open_status': 'Şu an Açık',
      'market_closed_status': 'Şu an Kapalı',
      'occupancy_rate': 'Doluluk Oranı',
      'address_label': 'Adres',
      'open_days_label': 'Açık Günler',
      'products_label': 'Ürünler',
      'general_products': 'Genel pazar ürünleri',
      'get_directions': 'Yol Tarifi Al (Google Haritalar)',
      'reviews_title': 'Yorumlar ve Puanlar',
      'rate_market': 'Pazarı Değerlendir',
      'comment_hint': 'Yorumunuzu buraya yazın...',
      'send_button': 'Gönder',
      'please_rate': 'Lütfen puan verin',
      'please_comment': 'Lütfen yorum yazın',
      'you': 'Siz',
      'today': 'Bugün',
      'search_placeholder': 'Pazar, ilçe veya ürün ara...',
      'no_results': 'Sonuç bulunamadı.',
      'filter_open_today': 'Bugün Açık',
      'filter_weekend': 'Hafta Sonu',
      'search_initial_message': 'Arama yapmak için yukarıya yazın.',
      'recent_searches': 'Son Aramalar',
      'clear_history': 'Geçmişi Temizle',
      'favorites_title': 'Favorilerim',
      'no_favorites': 'Henüz favori pazarınız yok.',
      'my_reviews': 'Yorumlarım',
      'no_reviews_yet': 'Henüz bir yorum yapmadınız.',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'pick_image_source': 'Fotoğraf Kaynağı',
      'remove_photo': 'Fotoğrafı Kaldır',
      'remove_photo_confirm_title': 'Fotoğrafı Kaldır',
      'remove_photo_confirm_message':
          'Profil fotoğrafınızı kaldırmak istediğinize emin misiniz?',
      'logout_confirmation_title': 'Çıkış Yap',
      'logout_confirmation_message': 'Çıkış yapmak istediğinize emin misiniz?',
      'yes': 'Evet',
      'no': 'Hayır',
      'register_success': 'Hesabınız başarıyla oluşturuldu.',
      'register_success_verify':
          'Hesabınız başarıyla oluşturuldu. Giriş yapabilirsiniz.',
      'forgot_password': 'Şifremi Unuttum',
      'forgot_password_title': 'Şifre Sıfırlama',
      'enter_email_message':
          'Lütfen kayıtlı e-posta adresinizi girin. Size şifre sıfırlama bağlantısı göndereceğiz.',
      'send_code': 'Bağlantı Gönder',
      'enter_code_message':
          'E-posta adresinize gönderilen 6 haneli kodu girin.',
      'verify_code': 'Doğrula',
      'new_password_label': 'Yeni Şifre',
      'reset_password_button': 'Şifreyi Yenile',
      'code_sent': 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
      'invalid_code': 'Geçersiz kod.',
      'password_reset_success':
          'Şifreniz başarıyla yenilendi. Giriş yapabilirsiniz.',
      'password_strength_very_weak': 'Çok Zayıf',
      'password_strength_weak': 'Zayıf',
      'password_strength_medium': 'Orta',
      'password_strength_good': 'İyi',
      'password_strength_strong': 'Güçlü',
      'check_email_timer': 'Lütfen e-postanızı kontrol edin.',
      'resend_available': 'E-posta gelmediyse tekrar gönderebilirsiniz.',
      'user_not_found': 'Bu e-posta adresiyle kayıtlı kullanıcı bulunamadı.',
      'delete_review_title': 'Yorumu Sil',
      'delete_review_confirm': 'Bu yorumu silmek istediğinize emin misiniz?',
      'delete_account': 'Hesabımı Sil',
      'delete_account_confirm_title': 'Hesabı Sil',
      'delete_account_confirm_message':
          'Hesabınızı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
      'onboarding_title_1': 'Pazarları Keşfet',
      'onboarding_desc_1':
          'Konumuna en yakın semt pazarlarını harita üzerinde gör ve yol tarifi al.',
      'onboarding_title_2': 'Güncel Bilgiler',
      'onboarding_desc_2':
          'Pazarların hangi gün açık olduğunu ve hangi ürünlerin satıldığını öğren.',
      'onboarding_title_3': 'Topluluğa Katıl',
      'onboarding_desc_3':
          'Pazarları değerlendir, yorum yap ve favorilerini kaydet.',
      'skip': 'Atla',
      'next': 'İleri',
      'start': 'Başla',
      'no_internet': 'İnternet bağlantısı yok',
      'theme_settings': 'Tema Ayarları',
      'select_color': 'Tema Rengi',
      'theme_mode': 'Görünüm Modu',
      'light': 'Aydınlık',
      'dark': 'Karanlık',
      'system': 'Sistem Teması',
      'or': 'veya',
      'google_login': 'Google ile Giriş Yap',
      'google_login_error': 'Google girişi başarısız',
      'welcome_dialog_title': 'Aramıza Hoş Geldin!',
      'welcome_dialog_message':
          'Kaydın başarıyla oluşturuldu. Pazaryeri uygulamasını keşfetmeye hemen başla.',
      'seller_panel_title': 'Satıcı Paneli',
      'change_market': 'Pazarı Değiştir',
      'select_market_title': 'Pazar Seçimi',
      'select_market_instruction': 'Satış yaptığınız pazarı seçiniz',
      'add_product_tab': 'Ürün Ekle',
      'reviews_tab': 'Değerlendirmeler',
      'product_name_label': 'Ürün Adı',
      'product_price_label': 'Fiyat (₺)',
      'product_desc_label': 'Ürün Açıklaması',
      'stall_location_label': 'Tezgah Tarifi',
      'stall_location_hint': 'Örn: Girişten sağa dönünce 3. tezgah',
      'add_photo_button': 'Fotoğraf Ekle',
      'publish_product_button': 'Ürünü Yayınla',
      'questions_title': 'Ürün Soruları',
      'reply_button': 'Yanıtla',
      'answer_hint': 'Yanıtınızı yazın...',
      'success_product_added': 'Ürün başarıyla eklendi!',
      'category_label': 'Kategori',
      'category_fruit': 'Meyve',
      'category_vegetable': 'Sebze',
      'category_delicatessen': 'Şarküteri',
      'category_error': 'Lütfen bir kategori seçin',
      'my_products_tab': 'Ürünlerim',
      'no_products_added': 'Henüz ürün eklemediniz.',
      'exit_seller_panel': 'Panelden Çık',
      'delete_product_title': 'Ürünü Sil',
      'delete_product_confirm': 'Bu ürünü silmek istediğinize emin misiniz?',
      'edit_product_title': 'Ürünü Düzenle',
      'update_button': 'Güncelle',
      'stock_status_label': 'Stok Durumu',
      'in_stock': 'Stokta Var',
      'out_of_stock': 'Stokta Yok',
      'view_count_label': 'Görüntülenme',
      'filter_all': 'Tümü',
      'filter_unanswered': 'Yanıtlanmamış Sorular',
      'filter_by_category': 'Kategoriye Göre Filtrele',
      'seller_settings_title': 'Satıcı Ayarları',
      'stall_name_label': 'Tezgah Adı',
      'stall_desc_label': 'Tezgah Açıklaması',
      'save_changes': 'Değişiklikleri Kaydet',
      'success_settings_updated': 'Ayarlar başarıyla güncellendi.',
      'stall_open': 'Açık',
      'stall_closed': 'Kapalı',
      'statistics_tab': 'İstatistikler',
      'stats_title': 'Satış İstatistikleri',
      'total_views': 'Toplam Görüntülenme',
      'most_viewed': 'En Çok Görüntülenen',
      'no_stats_data': 'Henüz istatistik verisi yok.',
      'total_products': 'Toplam Ürün',
      'total_sales': 'Toplam Satış',
      'total_revenue': 'Toplam Gelir',
      'critical_stock': 'Kritik Stok',
      'sellers_title': 'Satıcılar',
      'seller_details': 'Satıcı Detayı',
      'seller_products': 'Satıcının Ürünleri',
      'stall_location': 'Tezgah Konumu',
      'no_sellers_found': 'Bu pazarda henüz kayıtlı satıcı bulunmuyor.',
      'product_reviews': 'Ürün Değerlendirmeleri',
      'add_review': 'Yorum Ekle',
      'write_review_hint': 'Ürün hakkında düşünceleriniz...',
      'review_success': 'Yorumunuz başarıyla eklendi.',
      'no_reviews_for_product':
          'Bu ürün için henüz yorum yok. İlk yorumu siz yapın!',
      'seller_added_to_favorites': 'Satıcı favorilere eklendi.',
      'seller_removed_from_favorites': 'Satıcı favorilerden çıkarıldı.',
      'favorite_sellers_title': 'Favori Satıcılar',
      'no_favorite_sellers': 'Henüz favori satıcınız yok.',
      'phone_verification_title': 'Telefon Doğrulama',
      'enter_sms_code': 'Lütfen telefonunuza gelen 6 haneli kodu girin.',
      'verify_button': 'Doğrula',
      'resend_code': 'Kodu Tekrar Gönder',
      'verification_failed': 'Doğrulama başarısız. Lütfen tekrar deneyin.',
      'account_type_label': 'Hesap Türü',
      'stock_quantity_label': 'Stok Miktarı',
      'unit_label': 'Birim',
      'unit_kg': 'kg',
      'unit_piece': 'Adet',
      'unit_bunch': 'Demet',
      'low_stock_title': 'Stok Uyarısı',
      'low_stock_message': 'ürününün stoğu azaldı',
      'add_to_cart': 'Sepete Ekle',
      'insufficient_stock': 'Yetersiz Stok',
      'insufficient_stock_message': 'Stokta yeterli ürün yok. Mevcut stok:',
      'added_to_cart_success': 'Ürün sepete eklendi.',
      'connect_with_google': 'Google ile Hesabınızı Bağlayın',
    },
    'en': {
      'home_title': 'MARKETPLACE',
      'account_title': 'MY ACCOUNT',
      'login': 'Login',
      'logout': 'Logout',
      'register': 'Register',
      'dark_mode': 'Dark Mode',
      'language': 'Language / Dil',
      'welcome': 'Welcome',
      'guest_message':
          'Please login to view your account details and enjoy personal benefits.',
      'edit_profile': 'Edit Profile',
      'create_account': 'Create Account',
      'search_hint': 'Search product (e.g. apple)',
      'nearby_markets': 'Nearby Street Markets',
      'all_markets': 'All Markets',
      'settings': 'Settings',
      'location_refresh': 'Refresh Location',
      'customer_label': 'Customer',
      'seller_label': 'Seller',
      'select_user_type': 'Select User Type',
      'seller_login': 'Seller Login',
      'email_not_verified_message':
          'Your email address is not verified. Please check your inbox.',
      'resend_verification_email': 'Resend Verification Email',
      'verification_email_sent_success': 'Verification email sent again.',
      'cancel': 'Cancel',
      'remember_me': 'Remember Me',
      'search_tab': 'SEARCH',
      'report_tab': 'REPORT',
      'logout_success': 'Logged out successfully.',
      'location_title': 'Exact Location',
      'city': 'City',
      'coordinate': 'Coordinate',
      'location_updated': 'Location updated',
      'markets_loaded': 'markets loaded',
      'unknown': 'unknown',
      'selected_province': 'Selected province',
      'search_province_hint': 'Search province (e.g. Ist)',
      'clear_selection': 'Clear Selection',
      'error_prefix': 'Error',
      'location_settings': 'Location settings',
      'retry': 'Retry',
      'province_not_found': 'No markets found for province',
      'market_closed_today': 'Closed today',
      'market_open_today': 'Open today',
      'open_days_unknown': 'Open days unknown',
      'find_location': 'Find your location',
      'welcome_title': 'Welcome to Marketplace',
      'email_label': 'Email',
      'password_label': 'Password',
      'email_error': 'Please enter your email.',
      'password_error': 'Please enter your password.',
      'login_error': 'Incorrect email or password.',
      'no_account': 'Don\'t have an account? Register',
      'continue_guest': 'Continue without Login',
      'market_open_status': 'Open Now',
      'market_closed_status': 'Closed Now',
      'occupancy_rate': 'Occupancy Rate',
      'address_label': 'Address',
      'open_days_label': 'Open Days',
      'products_label': 'Products',
      'general_products': 'General market products',
      'get_directions': 'Get Directions (Google Maps)',
      'reviews_title': 'Reviews and Ratings',
      'rate_market': 'Rate Market',
      'comment_hint': 'Write your comment here...',
      'send_button': 'Send',
      'please_rate': 'Please rate',
      'please_comment': 'Please write a comment',
      'you': 'You',
      'today': 'Today',
      'search_placeholder': 'Search market, district or product...',
      'no_results': 'No results found.',
      'filter_open_today': 'Open Today',
      'filter_weekend': 'Weekend',
      'search_initial_message': 'Type above to search.',
      'recent_searches': 'Recent Searches',
      'clear_history': 'Clear History',
      'favorites_title': 'My Favorites',
      'no_favorites': 'No favorite markets yet.',
      'my_reviews': 'My Reviews',
      'no_reviews_yet': 'You haven\'t posted any reviews yet.',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'pick_image_source': 'Image Source',
      'remove_photo': 'Remove Photo',
      'remove_photo_confirm_title': 'Remove Photo',
      'remove_photo_confirm_message':
          'Are you sure you want to remove your profile photo?',
      'logout_confirmation_title': 'Logout',
      'logout_confirmation_message': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'register_success': 'Account created successfully.',
      'register_success_verify':
          'Account created successfully. You can now login.',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'enter_email_message':
          'Please enter your registered email address. We will send you a password reset link.',
      'send_code': 'Send Link',
      'enter_code_message': 'Enter the 6-digit code sent to your email.',
      'verify_code': 'Verify',
      'new_password_label': 'New Password',
      'reset_password_button': 'Reset Password',
      'code_sent': 'Password reset link sent to your email.',
      'invalid_code': 'Invalid code.',
      'password_reset_success':
          'Password reset successfully. You can now login.',
      'password_strength_very_weak': 'Very Weak',
      'password_strength_weak': 'Weak',
      'password_strength_medium': 'Medium',
      'password_strength_good': 'Good',
      'password_strength_strong': 'Strong',
      'check_email_timer': 'Please check your email.',
      'resend_available': 'If email not received, you can resend.',
      'user_not_found': 'No user found with this email address.',
      'delete_review_title': 'Delete Review',
      'delete_review_confirm': 'Are you sure you want to delete this review?',
      'delete_account': 'Delete Account',
      'delete_account_confirm_title': 'Delete Account',
      'delete_account_confirm_message':
          'Are you sure you want to delete your account? This action cannot be undone.',
      'onboarding_title_1': 'Discover Markets',
      'onboarding_desc_1':
          'Find the nearest street markets on the map and get directions.',
      'onboarding_title_2': 'Up-to-date Info',
      'onboarding_desc_2':
          'Learn which days markets are open and what products are sold.',
      'onboarding_title_3': 'Join the Community',
      'onboarding_desc_3':
          'Rate markets, leave comments and save your favorites.',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Start',
      'no_internet': 'No internet connection',
      'theme_settings': 'Theme Settings',
      'select_color': 'Theme Color',
      'theme_mode': 'Appearance Mode',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System Theme',
      'or': 'or',
      'google_login': 'Sign in with Google',
      'google_login_error': 'Google sign in failed',
      'welcome_dialog_title': 'Welcome Aboard!',
      'welcome_dialog_message':
          'Your account has been successfully created. Start exploring Marketplace now.',
      'seller_panel_title': 'Seller Panel',
      'change_market': 'Change Market',
      'select_market_title': 'Select Market',
      'select_market_instruction': 'Select the market you are selling at',
      'add_product_tab': 'Add Product',
      'reviews_tab': 'Reviews',
      'product_name_label': 'Product Name',
      'product_price_label': 'Price (₺)',
      'product_desc_label': 'Product Description',
      'stall_location_label': 'Stall Location',
      'stall_location_hint': 'e.g. 3rd stall after turning right at entrance',
      'add_photo_button': 'Add Photo',
      'publish_product_button': 'Publish Product',
      'questions_title': 'Product Questions',
      'reply_button': 'Reply',
      'answer_hint': 'Write your answer...',
      'success_product_added': 'Product added successfully!',
      'category_label': 'Category',
      'category_fruit': 'Fruit',
      'category_vegetable': 'Vegetable',
      'category_delicatessen': 'Delicatessen',
      'category_error': 'Please select a category',
      'my_products_tab': 'My Products',
      'no_products_added': 'No products added yet.',
      'exit_seller_panel': 'Exit Panel',
      'delete_product_title': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete this product?',
      'edit_product_title': 'Edit Product',
      'update_button': 'Update',
      'stock_status_label': 'Stock Status',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'view_count_label': 'Views',
      'filter_all': 'All',
      'filter_unanswered': 'Unanswered Questions',
      'filter_by_category': 'Filter by Category',
      'seller_settings_title': 'Seller Settings',
      'stall_name_label': 'Stall Name',
      'stall_desc_label': 'Stall Description',
      'save_changes': 'Save Changes',
      'success_settings_updated': 'Settings updated successfully.',
      'stall_open': 'Open',
      'stall_closed': 'Closed',
      'statistics_tab': 'Statistics',
      'stats_title': 'Sales Statistics',
      'total_views': 'Total Views',
      'most_viewed': 'Most Viewed',
      'no_stats_data': 'No statistics data yet.',
      'total_products': 'Total Products',
      'total_sales': 'Total Sales',
      'total_revenue': 'Total Revenue',
      'critical_stock': 'Critical Stock',
      'sellers_title': 'Sellers',
      'seller_details': 'Seller Details',
      'seller_products': 'Seller\'s Products',
      'stall_location': 'Stall Location',
      'no_sellers_found': 'No registered sellers found in this market yet.',
      'product_reviews': 'Product Reviews',
      'add_review': 'Add Review',
      'write_review_hint': 'Your thoughts about the product...',
      'review_success': 'Review added successfully.',
      'no_reviews_for_product':
          'No reviews for this product yet. Be the first to review!',
      'seller_added_to_favorites': 'Seller added to favorites.',
      'seller_removed_from_favorites': 'Seller removed from favorites.',
      'favorite_sellers_title': 'Favorite Sellers',
      'no_favorite_sellers': 'No favorite sellers yet.',
      'phone_verification_title': 'Phone Verification',
      'enter_sms_code': 'Please enter the 6-digit code sent to your phone.',
      'verify_button': 'Verify',
      'resend_code': 'Resend Code',
      'verification_failed': 'Verification failed. Please try again.',
      'account_type_label': 'Account Type',
      'stock_quantity_label': 'Stock Quantity',
      'unit_label': 'Unit',
      'unit_kg': 'kg',
      'unit_piece': 'Piece',
      'unit_bunch': 'Bunch',
      'low_stock_title': 'Stock Warning',
      'low_stock_message': 'stock is low',
      'add_to_cart': 'Add to Cart',
      'insufficient_stock': 'Insufficient Stock',
      'insufficient_stock_message': 'Not enough stock. Available:',
      'added_to_cart_success': 'Product added to cart.',
      'connect_with_google': 'Connect your account with Google',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
